2024-12-13 15:15:45,506 - WARNING - Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Рустам\PycharmProjects\pythonProject\venv\tests_12_4.py", line 32, in test_run
    runner2 = Runner(2)
              ^^^^^^^^^
  File "C:\Users\Рустам\PycharmProjects\pythonProject\venv\rt_with_exceptions.py", line 11, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-13 15:15:45,511 - WARNING - Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Рустам\PycharmProjects\pythonProject\venv\tests_12_4.py", line 19, in test_walk
    walker1 = Runner('blade_walker', -10)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Рустам\PycharmProjects\pythonProject\venv\rt_with_exceptions.py", line 16, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
